//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cihaz
    {
        public int Id { get; set; }
        public Nullable<int> TurId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string SeriNo { get; set; }
        public Nullable<System.DateTime> FaturaTarih { get; set; }
        public Nullable<int> SaticiFirmaId { get; set; }
        public string TakipNo { get; set; }
        public Nullable<int> GarantiBilgiId { get; set; }
        public Nullable<int> GenelDurumId { get; set; }
        public Nullable<int> ArizaId { get; set; }
        public string Aksesuar { get; set; }
        public Nullable<int> HasarDısGorunumId { get; set; }
        public Nullable<decimal> ParcaUcret { get; set; }
        public Nullable<decimal> İscilikUcret { get; set; }
        public Nullable<decimal> ArızaTespitUcret { get; set; }
        public Nullable<decimal> NakliyeUcret { get; set; }
        public Nullable<decimal> IskontoUcret { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
    
        public virtual GarantiBilgi GarantiBilgi { get; set; }
        public virtual Durum Durum { get; set; }
        public virtual Model Model { get; set; }
        public virtual SaticiFirma SaticiFirma { get; set; }
        public virtual CihazTur CihazTur { get; set; }
    }
}
