//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int Id { get; set; }
        public string MusteriAd { get; set; }
        public string Adres { get; set; }
        public string TelNo { get; set; }
        public string GsmNo { get; set; }
        public string Mail { get; set; }
        public string TCNo { get; set; }
        public System.DateTime GelisTarih { get; set; }
        public Nullable<int> CihazTurId { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string SeriNo { get; set; }
        public System.DateTime FaturaTarih { get; set; }
        public Nullable<int> SaticiFirmaId { get; set; }
        public string TakipNo { get; set; }
        public Nullable<int> GarantiBilgiId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<int> ArizaId { get; set; }
        public string Aksesuar { get; set; }
        public Nullable<int> HasarGorunumId { get; set; }
        public Nullable<int> IslemId { get; set; }
        public Nullable<decimal> ParcaUcret { get; set; }
        public Nullable<decimal> IscılıkUcret { get; set; }
        public Nullable<decimal> ArizaTespitUcret { get; set; }
        public Nullable<decimal> NakliyeUcret { get; set; }
        public Nullable<decimal> IskontoUcret { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
        public Nullable<int> ServisTurId { get; set; }
        public Nullable<int> DısServisBolgeId { get; set; }
        public System.DateTime DısServisGidisTarih { get; set; }
        public Nullable<int> AciklamaId { get; set; }
        public Nullable<int> ServisDurumId { get; set; }
        public Nullable<int> SonucId { get; set; }
        public System.DateTime BitisTarih { get; set; }
        public System.DateTime TeslimTarih { get; set; }
        public Nullable<int> TeslimSekilId { get; set; }
        public Nullable<int> KargoId { get; set; }
        public string KargoTakipNo { get; set; }
    
        public virtual Aciklama Aciklama { get; set; }
        public virtual Ariza Ariza { get; set; }
        public virtual CihazTur CihazTur { get; set; }
        public virtual DısServisBolge DısServisBolge { get; set; }
        public virtual Durum Durum { get; set; }
        public virtual GarantiBilgi GarantiBilgi { get; set; }
        public virtual HasarGorunum HasarGorunum { get; set; }
        public virtual Islem Islem { get; set; }
        public virtual Kargo Kargo { get; set; }
        public virtual ServisDurum ServisDurum { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual Model Model { get; set; }
        public virtual SaticiFirma SaticiFirma { get; set; }
        public virtual ServisTur ServisTur { get; set; }
        public virtual Sonuc Sonuc { get; set; }
        public virtual TeslimSekil TeslimSekil { get; set; }
    }
}
