//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int Id { get; set; }
        public Nullable<int> ServisTurId { get; set; }
        public Nullable<System.DateTime> GelisTarih { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<int> IslemId { get; set; }
        public Nullable<int> AciklamaId { get; set; }
        public Nullable<int> SonucId { get; set; }
        public Nullable<System.DateTime> BitisTarih { get; set; }
        public Nullable<System.DateTime> TeslimTarih { get; set; }
        public Nullable<int> TeslimSekilId { get; set; }
        public Nullable<int> KargoId { get; set; }
        public string KargoTakipNo { get; set; }
    }
}
