//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKayit
    {
        public int Id { get; set; }
        public string MusteriAd { get; set; }
        public System.DateTime GelisTarih { get; set; }
        public string CihazTur { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string SeriNo { get; set; }
        public string Aksesuar { get; set; }
        public string ServisTur { get; set; }
        public string ServisDurum { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
    }
}
