//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKayitDetay
    {
        public int Id { get; set; }
        public System.DateTime GelisTarih { get; set; }
        public string SeriNo { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
        public string CihazTur { get; set; }
        public string ServisDurum { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string MusteriAd { get; set; }
        public string Aksesuar { get; set; }
        public string Adres { get; set; }
        public string TelNo { get; set; }
        public string GsmNo { get; set; }
        public string Mail { get; set; }
        public string TCNo { get; set; }
        public System.DateTime FaturaTarih { get; set; }
        public string TakipNo { get; set; }
        public Nullable<decimal> ParcaUcret { get; set; }
        public Nullable<decimal> IscılıkUcret { get; set; }
        public Nullable<decimal> ArizaTespitUcret { get; set; }
        public Nullable<decimal> NakliyeUcret { get; set; }
        public Nullable<decimal> IskontoUcret { get; set; }
        public System.DateTime DısServisGidisTarih { get; set; }
        public System.DateTime BitisTarih { get; set; }
        public System.DateTime TeslimTarih { get; set; }
        public string KargoTakipNo { get; set; }
        public string Ariza { get; set; }
        public string DısServisBolge { get; set; }
        public string Durum { get; set; }
        public string HasarGorunum { get; set; }
        public string Islem { get; set; }
        public string Kargo { get; set; }
        public string SaticiFirma { get; set; }
        public string ServisTur { get; set; }
        public string Sonuc { get; set; }
        public string TeslimSekil { get; set; }
        public string GarantiBilgi { get; set; }
        public string Aciklama { get; set; }
    }
}
